### ISSUE TITLE
thetimes.co.uk not working

### ISSUE THREAD

**Issue by githubber244** [qnoum/bypass-paywalls-chrome-clean-magnolia1234#2]
Running the extension v 2.2.1.0 on Chrome 90.0.4430.212 on macOS and thetimes.co.uk is returning paywalls to me.

**Comment by qnoum** [comment]
I've created an issue at the original extension website:
https://gitlab.com/magnolia1234/bypass-paywalls-chrome-clean/-/issues/113
If you'd like to discuss please do it there considering similar issues in the future as well.
Here is just a mirror.
Thank you
