### ISSUE TITLE
unable to get automatic update with .crx file as per readme instr.

### ISSUE THREAD

**Issue by p060477** [qnoum/bypass-paywalls-chrome-clean-magnolia1234#2]
![just click update but still old release vers  2 1 7 0 instead of 2 1 8 0](https://user-images.githubusercontent.com/12773559/116008985-5c6c6b80-a617-11eb-8454-fbd62a4d671d.jpg)

in readme instr.  is written that having whitelisted the extension in chorme :
by running as admin this .reg file:
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\ExtensionInstallWhitelist]
"1"="lkbebcjgcmobigpeffafkodonchffocl"

and having the .crx file i will get automatic updates..
but as you see it is untrue...
NB: this is a screen shoot done -after- having clicking and re-clicking the update-button...;)

**Comment by qnoum** [comment]
here is just a mirror,
please address this issue at the original site:
https://gitlab.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by p060477** [comment]
first thxs so much!
..done..but the person who make the -wrong readme- 
in which there is written that big mistake about the automatic updates for .crx file
 is the same who lead the page and reply in a chaotic way to the issues...
i've lost the last precious days of my time following his so chaotic instrucions..
and the final result is the one i've just attached here...
before wasting my and yr time here i've tried to post this also where you suggest me..
but the chaotic person is only able, not to make autom.updates run,
but to delete the issue i created...
so i really hope that here on github someone more polite of him 
should be much more helpfull and un-chaotic.. ;)
thxs so much for yr kind attention
cheers!

**Comment by qnoum** [comment]
Well I maybe less chaotic (which I honestly doubt) but I don't have a tiniest clue about javascript.
So you'll have to try to settle your issue with magnolia, sorry mate.
Maybe search there among already existing issues on gitlab,
somebody could have had the same problem as you. 
Cheers!

**Comment by p060477** [comment]
with a guy who do not want to admin its fault, as a dev.,
 and instead of learn of it is only able to delete the issues related to its chaotic error
 i've no chance to settle...:(
i hope here someone read this and discover a trick or solve the bug..
thxs for yr kind attn
cheers!

**Comment by qnoum** [comment]
I am afraid there is nobody here apart from me, 
since people usually go to the original website. 

If your chrome doesn't update the extension automatically, 
try to download crx file and install it directly.

I don't use chrome but I have brave and it also uses crx files.
As far as I can see it has updated automatically to 2.1.8.0
Which is faster than my firefox which still uses 2.1.7.0

**Comment by p060477** [comment]
thxs again for yr kind helping,
"try to download crx file and install it directly."...:
done...the screen shoot above is with the crx file...but ..it really do not update...still at 2.1.7.0...

**Comment by qnoum** [comment]
Do it the hard way to be sure, this Windows Registry stuff is too shady to work anyway.
Cheers

**Comment by p060477** [comment]
thxs again indeed!
you are so very very kind!
but in the readme is written:

Load unpacked: Chrome (desktop), Microsoft Edge (Chromium)/Brave/Yandex

or 'whitelist' extension and install automatically updating crx-file (see next section)

**Comment by p060477** [comment]
and how you are able to use crx of BPC in Brave..??..if i try it i install it but i alweays have it greyed..so -off- and not able to turn on...the strange thing is that :
in chrome i'm able to upload the crx and have it non greyed so in on state
but this did not update automatically
in brave is exactly the contrary... i upload the crx file..is greyed so is off state..but if i click on the -update- button it goes from 2.1.7.0 to latest 2.1.8.0...so really very strange behaviour...
anyway how you are able to have bpc crx file in state -on- in brave..??
thxs so much again!
cheers

**Comment by qnoum** [comment]
It was long ago so I don't remember how I did it initially in Brave,  
but since then it updates on it's own without any troubles.
I have just installed BPC 2.1.8.0 to chrome via zip folder and it works fine.

**Comment by p060477** [comment]
first so many thxs again for yr kind support,
yes if you load unpacked it works..the problem is,and the reason why i open the issue, that ,unlike as clerly written in readme by dev, it is impossible in chrome to have it automatically updated...
cause the only way the dev indicated: by crx file.., is undubtley -wrong- 
and remains the mistery of brave...caudse i've the very latest vers 1.23 and is really not possible to have BPC -on-...
it's so real a very mistery...
anyway the issue of impossible to have automatiucally updates in chrome remains..
thxs again for yr kindness
cheers!

**Comment by p060477** [comment]
done lots of searches..:
see this as ex.:
https://github.com/brave/brave-browser/issues/9797
..there is really no way to add crx in brave and have this working -on-...
and so this is another great mistake done in the readme by magnolia....
how many chaotic things...
lots of mistakes there...
result:
no way to automat.updates in chrome
no way to have crx file working in brave
thxs so much again for yr kind helping
you are very very kind
cheers

**Comment by qnoum** [comment]
Well maybe brave also needs a folder to get it work,
I honestly don't remember how exactly I've launched it for the first time.
And I can't figure out why it works in my brave and not in yours.

As for the impossibility of auto-updates in chrome - I guess we have tough luck.
You know that google wouldn't allow magnolia's addon on it's webstore,
so maybe that's the reason for it or at least in part.

**Comment by p060477** [comment]
txs so much indeed again!
last question. when there is an update chrome and brave initially block it so the new vers, for ex the new 2.1.8.0 is in off line mode and we have always to manage it clicking to have it from off to on  state
is there a way to prevent it..??..or being out of chrome and brave web store this browser's behaviour is impossible to prevent..??
again thxs so much for yr kind helping in a very clear and gentle way
thanks again!
cheers!

**Comment by qnoum** [comment]
Thing is, by me Brave extension magically updates on it's own,
and in Chrome I've just installed the latest version.
So I can't reproduce the situation where it refuses to update.
I never saw it becoming grey as you describe.
Maybe it will, but then I'll just delete it and download the newest zip.

**Comment by p060477** [comment]
yes the update is on its own but when is updated,for ex from 2.1.7.0 to 2.1.8.0 the extension is also in -on- state?
or even if updated you have to permitt it in order to re-became in -on- state..?
chrome or brave do not ask nothing about permission when the ext is updated..??
thxs so much again for yr kind and precious help
cheers!

**Comment by qnoum** [comment]
when it updates it only asks to allow using it in private windows, which I gladly permit.

**Comment by p060477** [comment]
"it only asks to allow "..:
Yes!.. i'm talking  just about this..
and i ask you if there is a way not to have this "ask to allow"
 but to set the browser,chrome or brave,
not to need this my action, as it was automatically allowed without the need of my 
action on every update
thxs so much from the very deep of my heart for yr kind attention and gentle helping
cheers!

**Comment by qnoum** [comment]
no there's no roundabout it, not that I know of.

**Comment by p060477** [comment]
thxs so much indeed for yr very precious helping
and for yr kindness and patience too
wish you all the best!
cheers!
:)

**Comment by qnoum** [comment]
you're welcome
have a nice day
